### ISSUE TITLE
终点站的结构是不是和 misakaf 一样的

### ISSUE THREAD

**Issue by NPCDW** [lateautumn2/MisakaF-nginx-reProxy#1]
纸片人的地址漏了，43行

**Comment by lateautumn2** [comment]
感谢，已修改
-- 
终点站的结构是不是和 misakaf 一样的
> 我没有终点站的账号，所以对此不清楚，不过目前emby只有两种，例misakaf类播放分离，例HXD类播放不分离；
播放不分离只需要处理   location / 中的 proxy_pass和 proxy_redirect ，没有单独推流域名，前端域名即推流域名。

**Comment by NPCDW** [comment]
感谢，刚试了一下，终点站的推流域名和 web 域名是一样的，代理一个域名就可以了，
之前一直以为服务器返回多个不同的域是无法代理的，又学到了
